export const exportMessages = {
  en: {
    actions: 'Actions for {name}', convert: 'Convert', start: 'Start conversion', type: 'Output type', video: 'Video', audio: 'Audio', format: 'Format', quality: 'Quality', compact: 'Compact', balanced: 'Balanced', high: 'High', filename: 'Output filename', destination: 'Saved in {folder} under your download folder. The original is preserved.', copy: 'Copy compatible streams without re-encoding', encode: 'Re-encoding uses the selected quality. Higher quality cannot restore lost detail.', copyHelp: 'Stream copy changes the container without changing the selected encoded streams.', acknowledge: 'I understand these preservation limits.', limits: 'Only the first video and audio tracks are selected. Extra tracks, subtitles, and attachments are omitted. Tags depend on the target format; artwork is preserved only when supported. Chapters are retained only for full-length MP4/MKV exports.', added: 'Added to Processes', view: 'View process', converted: 'Converted', edited: 'Edited', unavailable: 'No supported output is available. Check the managed FFmpeg runtime in Settings.', failed: 'Could not start processing. Check the source and runtime, then try again.', loadFailed: 'Could not inspect this file. Check the source and runtime, then retry.', source: 'Source: {duration} s · {dimensions}',
  },
  ru: {
    actions: 'Действия с {name}', convert: 'Конвертировать', start: 'Начать конвертацию', type: 'Тип результата', video: 'Видео', audio: 'Аудио', format: 'Формат', quality: 'Качество', compact: 'Компактное', balanced: 'Сбалансированное', high: 'Высокое', filename: 'Имя выходного файла', destination: 'Сохранение в {folder} в папке загрузок. Оригинал сохраняется.', copy: 'Копировать совместимые потоки без перекодирования', encode: 'Перекодирование использует выбранное качество. Высокое качество не восстанавливает потерянные детали.', copyHelp: 'Копирование меняет контейнер, сохраняя выбранные закодированные потоки.', acknowledge: 'Я понимаю ограничения сохранения данных.', limits: 'Выбираются первые видео- и аудиодорожки. Остальные дорожки, субтитры и вложения пропускаются. Теги зависят от формата; обложка сохраняется, если поддерживается. Главы сохраняются только при полном экспорте в MP4/MKV.', added: 'Добавлено в процессы', view: 'Показать процесс', converted: 'Конвертировано', edited: 'Отредактировано', unavailable: 'Нет доступного формата. Проверьте FFmpeg в настройках.', failed: 'Не удалось начать обработку. Проверьте исходный файл и среду выполнения, затем повторите.', loadFailed: 'Не удалось проверить файл. Проверьте исходный файл и среду выполнения, затем повторите.', source: 'Источник: {duration} с · {dimensions}',
  },
  tg: {
    actions: 'Амалҳо барои {name}', convert: 'Табдил додан', start: 'Оғози табдил', type: 'Навъи натиҷа', video: 'Видео', audio: 'Аудио', format: 'Формат', quality: 'Сифат', compact: 'Ҳаҷми хурд', balanced: 'Мутавозин', high: 'Баланд', filename: 'Номи файли натиҷа', destination: 'Дар {folder} дар ҷузвдони боргирӣ сабт мешавад. Асл нигоҳ дошта мешавад.', copy: 'Нусхабардории ҷараёнҳои мувофиқ бе рамзгузории дубора', encode: 'Рамзгузории дубора сифати интихобшударо истифода мебарад. Сифати баланд ҷузъиёти гумшударо барқарор намекунад.', copyHelp: 'Нусхабардорӣ контейнерро иваз карда, ҷараёнҳои интихобшударо нигоҳ медорад.', acknowledge: 'Ман маҳдудиятҳои нигоҳдории маълумотро мефаҳмам.', limits: 'Танҳо роҳҳои аввалини видео ва аудио интихоб мешаванд. Роҳҳои иловагӣ, зернависҳо ва замимаҳо партофта мешаванд. Тегҳо аз формат вобастаанд; муқова танҳо ҳангоми дастгирӣ нигоҳ дошта мешавад. Бобҳо танҳо дар содироти пурраи MP4/MKV нигоҳ дошта мешаванд.', added: 'Ба равандҳо илова шуд', view: 'Нишон додани раванд', converted: 'Табдилшуда', edited: 'Таҳриршуда', unavailable: 'Формати дастгиришаванда нест. FFmpeg-ро дар танзимот санҷед.', failed: 'Оғози коркард нашуд. Файли аслӣ ва муҳити иҷроро санҷида, такрор кунед.', loadFailed: 'Санҷиши файл нашуд. Файли аслӣ ва муҳити иҷроро санҷида, такрор кунед.', source: 'Манбаъ: {duration} с · {dimensions}',
  },
}
