export const exportMessages = {
  en: {
    conflict: 'The source changed or is busy. Close and reopen this form to inspect the current file.', runtimeError: 'FFmpeg or FFprobe is unavailable. Repair the managed runtime in Settings and retry.', missing: 'The source file is missing. Refresh the Completed library and choose an available file.', invalid: 'The selected options are unsupported. Check times, dimensions, filename and format.', diskError: 'Cannot save the output. Check free space, folder permissions and filesystem hard-link support.', connectionError: 'The response was lost. Check Processes before submitting again to avoid duplicate work.', nameHelp: 'Use a basename without an extension, separators or reserved system names (up to 180 UTF-8 bytes).',
    actions: 'Actions for {name}', convert: 'Convert', start: 'Start conversion', type: 'Output type', video: 'Video', audio: 'Audio', format: 'Format', quality: 'Quality', compact: 'Compact', balanced: 'Balanced', high: 'High', filename: 'Output filename', destination: 'Saved in {folder} under your download folder. The original is preserved.', copy: 'Copy compatible streams without re-encoding', encode: 'Re-encoding uses the selected quality. Higher quality cannot restore lost detail.', copyHelp: 'Stream copy changes the container without changing the selected encoded streams.', acknowledge: 'I understand these preservation limits.', limits: 'Only the first video and audio tracks are selected. Extra tracks, subtitles, and attachments are omitted. Tags depend on the target format; artwork is preserved only when supported. Chapters are retained only for full-length MP4/MKV exports.', added: 'Added to Processes', view: 'View process', converted: 'Converted', edited: 'Edited', unavailable: 'No supported output is available. Check the managed FFmpeg runtime in Settings.', failed: 'Could not start processing. Check the source and runtime, then try again.', loadFailed: 'Could not inspect this file. Check the source and runtime, then retry.', source: 'Source: {duration} s · {dimensions}',
  },
  ru: {
    conflict: 'Исходный файл изменён или занят. Закройте и откройте форму, чтобы проверить актуальный файл.', runtimeError: 'FFmpeg или FFprobe недоступен. Восстановите среду выполнения в настройках и повторите.', missing: 'Исходный файл отсутствует. Обновите библиотеку и выберите доступный файл.', invalid: 'Выбранные параметры не поддерживаются. Проверьте время, размеры, имя и формат.', diskError: 'Не удалось сохранить файл. Проверьте свободное место, права папки и поддержку жёстких ссылок.', connectionError: 'Ответ потерян. Проверьте процессы перед повторной отправкой, чтобы избежать дублирования.', nameHelp: 'Имя без расширения, разделителей и системных зарезервированных имён (до 180 байт UTF-8).',
    actions: 'Действия с {name}', convert: 'Конвертировать', start: 'Начать конвертацию', type: 'Тип результата', video: 'Видео', audio: 'Аудио', format: 'Формат', quality: 'Качество', compact: 'Компактное', balanced: 'Сбалансированное', high: 'Высокое', filename: 'Имя выходного файла', destination: 'Сохранение в {folder} в папке загрузок. Оригинал сохраняется.', copy: 'Копировать совместимые потоки без перекодирования', encode: 'Перекодирование использует выбранное качество. Высокое качество не восстанавливает потерянные детали.', copyHelp: 'Копирование меняет контейнер, сохраняя выбранные закодированные потоки.', acknowledge: 'Я понимаю ограничения сохранения данных.', limits: 'Выбираются первые видео- и аудиодорожки. Остальные дорожки, субтитры и вложения пропускаются. Теги зависят от формата; обложка сохраняется, если поддерживается. Главы сохраняются только при полном экспорте в MP4/MKV.', added: 'Добавлено в процессы', view: 'Показать процесс', converted: 'Конвертировано', edited: 'Отредактировано', unavailable: 'Нет доступного формата. Проверьте FFmpeg в настройках.', failed: 'Не удалось начать обработку. Проверьте исходный файл и среду выполнения, затем повторите.', loadFailed: 'Не удалось проверить файл. Проверьте исходный файл и среду выполнения, затем повторите.', source: 'Источник: {duration} с · {dimensions}',
  },
  tg: {
    conflict: 'Файли аслӣ тағйир ёфтааст ё банд аст. Барои санҷидани файли ҷорӣ шаклро пӯшида боз кушоед.', runtimeError: 'FFmpeg ё FFprobe дастрас нест. Муҳити иҷроро дар танзимот таъмир карда такрор кунед.', missing: 'Файли аслӣ нест. Китобхонаро нав карда файли дастрасро интихоб кунед.', invalid: 'Параметрҳои интихобшуда дастгирӣ намешаванд. Вақт, андоза, ном ва форматро санҷед.', diskError: 'Сабти файл нашуд. Ҷойи холӣ, иҷозати ҷузвдон ва дастгирии пайвандҳои сахтро санҷед.', connectionError: 'Ҷавоб гум шуд. Пеш аз фиристодани дубора равандҳоро санҷед, то кор такрор нашавад.', nameHelp: 'Номи бе пасванд, ҷудокунанда ва номҳои ҳифзшудаи система (то 180 байти UTF-8).',
    actions: 'Амалҳо барои {name}', convert: 'Табдил додан', start: 'Оғози табдил', type: 'Навъи натиҷа', video: 'Видео', audio: 'Аудио', format: 'Формат', quality: 'Сифат', compact: 'Ҳаҷми хурд', balanced: 'Мутавозин', high: 'Баланд', filename: 'Номи файли натиҷа', destination: 'Дар {folder} дар ҷузвдони боргирӣ сабт мешавад. Асл нигоҳ дошта мешавад.', copy: 'Нусхабардории ҷараёнҳои мувофиқ бе рамзгузории дубора', encode: 'Рамзгузории дубора сифати интихобшударо истифода мебарад. Сифати баланд ҷузъиёти гумшударо барқарор намекунад.', copyHelp: 'Нусхабардорӣ контейнерро иваз карда, ҷараёнҳои интихобшударо нигоҳ медорад.', acknowledge: 'Ман маҳдудиятҳои нигоҳдории маълумотро мефаҳмам.', limits: 'Танҳо роҳҳои аввалини видео ва аудио интихоб мешаванд. Роҳҳои иловагӣ, зернависҳо ва замимаҳо партофта мешаванд. Тегҳо аз формат вобастаанд; муқова танҳо ҳангоми дастгирӣ нигоҳ дошта мешавад. Бобҳо танҳо дар содироти пурраи MP4/MKV нигоҳ дошта мешаванд.', added: 'Ба равандҳо илова шуд', view: 'Нишон додани раванд', converted: 'Табдилшуда', edited: 'Таҳриршуда', unavailable: 'Формати дастгиришаванда нест. FFmpeg-ро дар танзимот санҷед.', failed: 'Оғози коркард нашуд. Файли аслӣ ва муҳити иҷроро санҷида, такрор кунед.', loadFailed: 'Санҷиши файл нашуд. Файли аслӣ ва муҳити иҷроро санҷида, такрор кунед.', source: 'Манбаъ: {duration} с · {dimensions}',
  },
}
